---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-general.yml@b4f6567d034c6d1fc45823b4fce385e211e57993  # master
